# 线上配置文件

spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partner_matching_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Yu610811
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0

